---
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      #  - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    # replace with your own volumes path on your device
    volumes:
      - ./jellyfin/config:/config
      - /srv/dev-disk-by-uuid-f7021574-ef73-4987-a726-d4176679f14f/share/TVShows:/data/tvshows
      - /srv/dev-disk-by-uuid-f7021574-ef73-4987-a726-d4176679f14f/share/Movies:/data/movies
      - /srv/dev-disk-by-uuid-f7021574-ef73-4987-a726-d4176679f14f/share/Videos:/data/videos
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
